### ISSUE TITLE
Add Logo

### ISSUE THREAD

**Issue by nataliepina** [nataliepina/GrowersBrains#21]
Once we have a logo let's add it throughout the app

**Comment by robpedersendev** [comment]
Here is our final logo according to Som 
[GrowersBrainFinalLogo.zip](https://github.com/nataliepina/GrowersBrains/files/5088237/GrowersBrainFinalLogo.zip)
![image](https://user-images.githubusercontent.com/40696979/90471115-88c00780-e0da-11ea-983c-1b07a2f44ec8.png)

**Comment by robpedersendev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Logo to the website](https://trello.com/c/Dsu1K4ha/4-add-logo-to-the-website)

**Comment by robpedersendev** [comment]
This is not yet finalized.
