### ISSUE TITLE
Hero Section

### ISSUE THREAD

**Issue by nataliepina** [nataliepina/GrowersBrains#23]
We'll need the hero section added. Please refer to the images in the public folder and move them into an assets folder in your page to use. 
![Screen Shot 2020-08-13 at 2 19 26 PM](https://user-images.githubusercontent.com/34781875/90177338-00ef9b80-dd70-11ea-8fed-ac62be88687e.png)

**Comment by nuggetnchill** [comment]
I can try to tackle this
