### ISSUE TITLE
Bugfix:  Route app to home page when it starts instead of Error 404

### ISSUE THREAD

**Issue by nataliepina** [nataliepina/GrowersBrains#31]
There is a routing issue when you start the app it loading the error404 page.

**Comment by benjaminloeffel** [comment]
@nataliepina  

On application start the terminal logs the message: `webpack output is served from /GrowersBrains`.

Create React App assumes the application is hosted at the serving web server's root or a subpath as specified in `package.json` `"homepage": "https://nataliepina.github.io/GrowersBrains",`.

`homepage` in the `package.json` is a requirement for `gh-pages` and we cannot work around it by [serving the same build from different paths](https://create-react-app.dev/docs/deployment/#serving-the-same-build-from-different-paths)

There is a related issue on [StackOverflow](https://stackoverflow.com/questions/43011207/using-homepage-in-package-json-without-messing-up-paths-for-localhost)

The simplest solution appears to be creating an `.env` file with `PUBLIC_URL=/` in the local development environment
