### ISSUE TITLE
Add .env files to gitignore file

### ISSUE THREAD

**Issue by vyasriday** [nataliepina/GrowersBrains#39]

**Comment by robpedersendev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create a .env.example file for our project that contains an example of what to use for your .ENV file in the project.](https://trello.com/c/hGYgyKqQ/9-create-a-envexample-file-for-our-project-that-contains-an-example-of-what-to-use-for-your-env-file-in-the-project)

**Comment by vyasriday** [comment]
> ![](https://camo.githubusercontent.com/193766a3b9959c5f4ed5cd8cf3251d015e839d51/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [Create a .env.example file for our project that contains an example of what to use for your .ENV file in the project.](https://trello.com/c/hGYgyKqQ/9-create-a-envexample-file-for-our-project-that-contains-an-example-of-what-to-use-for-your-env-file-in-the-project)

This is the wrong task added attached to the issue
