### ISSUE TITLE
Implement CI/CD branches

### ISSUE THREAD

**Issue by robpedersendev** [nataliepina/GrowersBrains#44]
Develop: for features 

Staging: merged with develop checked for erroneous behaviour with cypress and sentry 

Production: our face outward and should be used for public and review
With CI/CD it puts our github repo through series of automatic tests ... check linting, prettier and tests cases. Then if all good uploads, build and host on Amazon services.

**Comment by robpedersendev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement CI/CD branches](https://trello.com/c/us9lG3WE/11-implement-ci-cd-branches)

**Comment by jerome0caruso** [comment]
I created Staging and Develop branches.  Couldn't make a pull request because master and Staging are identical.

**Comment by robpedersendev** [comment]
Thanks for taking care of this @jerome0caruso
